// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivruuzqqygepvpmcbimo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cnV1enFxeWdlcHZwbWNiaW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTIwMjEsImV4cCI6MjA2MTc2ODAyMX0.bYJ3kjIpWrP16iB8vMGDLA2vwfFHXVHjncQPrr2rSYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);